### ISSUE TITLE
**Bug Fix - Service**

### ISSUE THREAD

**Issue by harunurkst** [rabiulislam993/shonirvor#15]
- [ ] Change Model Name to Service
- [ ] Change provider to ForeignKey(User)

**Comment by siyam04** [comment]
আমরা টাস্ক ২ টা কমপ্লিট করেছি। এখন রেজিস্ট্রেশন এবং লগিন পার্ট শেষ না করা পর্যন্ত আমাদের প্রোজেক্টের সার্ভিস ব্রাঞ্চ কাজ করবেনা। কারন আমাদের সার্ভিস এর প্রোভাইডার রেজিস্ট্রেশনের এবং লগিনের ইউজারের সাথে কানেক্টেড।
